name: arboles-info-maps
region: ams

services:
  - name: web
    image:
      registry_type: DOCR
      registry: arboles-info
      repository: arboles-info-maps
      tag: latest
    
    instance_count: 1
    instance_size_slug: basic-xs
    
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
    
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_TIME
        type: GENERAL
      
      - key: DEBUG
        value: "False"
        scope: RUN_TIME
        type: GENERAL
      
      - key: ALLOWED_HOSTS
        value: "${APP_DOMAIN},*"
        scope: RUN_TIME
        type: GENERAL
      
      - key: SECRET_KEY
        value: "${SECRET_KEY}"
        scope: RUN_TIME
        type: SECRET
    
    http_port: 8080
    routes:
      - path: /
