[behave]
show_skipped = false
show_timings = true
format = pretty
color = true
stdout_capture = false
stderr_capture = false
log_capture = false
junit = true
junit_directory = test-reports

[behave.userdata]
# Custom user data for behave tests
overpass_timeout = 60
